[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_ENDPOINT}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }